DISEASE_ONTOLOGY_ID: "14330"
RNA_DISEASE_SCORE: "0.65"

DISEASE_KEYWORD: "parkinson"

NCIT_DISEASE_TERM: "C0030567"
DISGENET_SCORE: "0.3"
DISGENET_PUBLICATION_LIMIT: "15"

PUBCHEM_DISEASE_ID: "DZID8805"

EXPERIMENTAL_FACTOR_ONTOLOGY_ID: "MONDO_0021095"
TEXT_FILE_WITH_ENSEMBL_GENE_IDs: "168genes.txt"

OUTPUT_PREFIX: "20240208"